version: '3.9'

services:

  mariadb:
    image: mariadb:10.9.4-jammy
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - ./sql:/tmp
    environment:
      MYSQL_ROOT_PASSWORD: root
